setpref targetPlatformPath=${platform}
import --properties ${source}/org.fusesource.tools.messaging.build/buckminster.properties ${source}/org.fusesource.tools.messaging.build/msgo.cquery 
build --properties ${source}/org.fusesource.tools.messaging.build/buckminster.properties 
perform --properties ${source}/org.fusesource.tools.messaging.build/buckminster.properties org.fusesource.tools.messaging.build#site.p2.zip  
